### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by tolsadus** [PentesterES/AndroidPINCrack#1]
Hi,

Awesome work by the way at the defcon for the "Breaking SSL Using Time Synchronisation Attacks".
Just wanted to know if you could add a README.md for the AndroidPINCrack repo ? :computer: 

Muchas gracias senor :+1:

**Comment by jselvi** [comment]
I copied the information from my old repository: http://tools.pentester.es/androidpincrack

**Comment by tolsadus** [comment]
Perfect :lock: Thanks !
