### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aravtech** [PentesterES/AndroidPINCrack#2]
![Screenshot_20200801_081739_com.termux.jpg](https://user-images.githubusercontent.com/69064471/89092449-8ddd4100-d3cf-11ea-95cd-560ca4e0ed4e.jpg)
What is my error
How can I resolve it

**Comment by jselvi** [comment]
hey @Aravtech, basically I coded this many years ago, and it was never ported to Python3. It was just a matter or changing the way I use "print" and now it seems to be working. Fixed here: https://github.com/PentesterES/AndroidPINCrack/commit/baabb66cbdee1e35d1554326ddc94720dbedc940

However, please note that I haven't used this for many years, so I don't know if it still works with modern Android devices. If you see that you need to change something to make it work in modern devices, feel free to send a pull request and I'll be happy to merge it and give you the credit for it.
