### ISSUE TITLE
could someone tell me how to solve the problem or what is it due to? I tried a bit of everything but I don't understand why it does this, as soon as I open the program the window pops up and tells me to close it.

### ISSUE THREAD

**Issue by nikybimon** [PentesterES/AndroidPINCrack#3]
https://user-images.githubusercontent.com/77247440/104134615-1a325d80-538b-11eb-8650-17c8b3b5e681.mp4

**Comment by jselvi** [comment]
Hey @nikybimon, it's a command line tool, not GUI. You need to use flags from the command line to make it work.

https://en.m.wikipedia.org/wiki/Command-line_interface

If you are not familiar with this kind of interfaces, I would recommend you to get used to them before trying to use this tool. Anyway, I haven't used it for years. I don't know if it still works in modern Android devices.
