### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by officialkingiv** [PentesterES/AndroidPINCrack#4]
can you plz explain how to use it 
i downloaded this in my kali Linux pc and i connected my phone to my pc with usb and i want lunch it 
but i don't know how to do it plz help me out

**Comment by jselvi** [comment]
hey @officialkingiv, I guess you didn't read the README file, right? It's explained there. There's also a warning in the README file because I haven't use this tool for years, and I honestly think it won't work with modern Android versions.
